"""Add hashed_password column to users

Revision ID: cc0eba4bee70
Revises: 71727a3032b3
Create Date: 2025-05-26 11:46:33.627732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc0eba4bee70'
down_revision: Union[str, None] = '71727a3032b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # Step 1: Add column as nullable
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    
    # Step 2: Fill default password for existing users
    from passlib.context import CryptContext
    pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
    hashed_default = pwd_context.hash("default_password")
    op.execute(f"UPDATE users SET hashed_password = '{hashed_default}'")
    
    # Step 3: Alter column to be NOT NULL
    op.alter_column('users', 'hashed_password', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
